import { describe, expect, it } from 'vitest';
import {
  buildContextBlock,
  buildExplainMessages,
  buildSystemPrompt,
  createSseParser,
  formatCost,
  transcriptWindow,
} from '../src/lib/explain';
import { isExplainRequest, isM24989PageRequest } from '../src/lib/messages';
import type { ExplainContext, ExplainRequest } from '../src/lib/messages';

function context(overrides: Partial<ExplainContext> = {}): ExplainContext {
  const cues = Array.from({ length: 100 }, (_, i) => ({
    text: `台詞${i}`,
    startMs: i * 2_000,
    endMs: i * 2_000 + 1_500,
  }));
  return {
    site: 'netflix',
    title: 'Show S1E2 — Episode',
    details: [{ label: 'Series', value: 'Show' }],
    autoGenerated: false,
    language: 'ja',
    cues,
    from: 40,
    to: 41,
    selectedText: '台詞40',
    ...overrides,
  };
}

describe('transcriptWindow', () => {
  it('stops a short lookahead after the selection', () => {
    const w = transcriptWindow(context());
    expect(w.cues[0]!.index).toBe(0);
    expect(w.cues.at(-1)!.index).toBe(61);
    expect(w.omittedBefore).toBe(false);
    expect(w.omittedAfter).toBe(true);
  });

  it('drops the earliest cues first when over budget, never the selection', () => {
    const w = transcriptWindow(context(), 200);
    expect(w.omittedBefore).toBe(true);
    expect(w.cues.some((c) => c.index === 40)).toBe(true);
    expect(w.cues.some((c) => c.index === 41)).toBe(true);
    expect(w.cues[0]!.index).toBeGreaterThan(0);
  });
});

describe('prompt', () => {
  it('marks selected lines and includes video details', () => {
    const block = buildContextBlock(context());
    expect(block).toContain('Site: Netflix');
    expect(block).toContain('Series: Show');
    expect(block).toContain('▶ [01:20] 台詞40');
    expect(block).toContain('▶ [01:22] 台詞41');
    expect(block).not.toContain('▶ [01:18]');
    expect(block).not.toContain('台詞62');
    expect(block).toContain('<selection>台詞40</selection>');
  });

  it('declares auto-generated transcripts at the top', () => {
    expect(buildSystemPrompt(context({ autoGenerated: true }), 'English')).toMatch(/^IMPORTANT: .*auto-generated/);
    expect(buildSystemPrompt(context(), 'English')).not.toContain('auto-generated');
  });

  it('writes in the configured language', () => {
    expect(buildSystemPrompt(context(), 'German')).toContain('Write in German.');
  });

  it('keeps the context as a cached first user part across follow-ups', () => {
    const request: ExplainRequest = {
      context: context(),
      history: [{ question: '', answer: 'First answer' }],
      question: 'Why not です?',
    };
    const messages = buildExplainMessages(request, 'English');
    expect(messages.map((m) => m.role)).toEqual(['system', 'user', 'assistant', 'user']);
    const first = messages[1]!.content;
    expect(Array.isArray(first) && first[0]!.cache_control).toEqual({ type: 'ephemeral' });
    expect(Array.isArray(first) && first[1]!.text).toBe('Explain the selected text.');
    expect(messages[2]!.content).toBe('First answer');
    expect(messages[3]!.content).toBe('Why not です?');
  });
});

describe('formatCost', () => {
  it('formats small and regular amounts', () => {
    expect(formatCost(0.0314)).toBe('$0.031');
    expect(formatCost(0.004123)).toBe('$0.00412');
    expect(formatCost(0)).toBe('$0');
  });
});

describe('createSseParser', () => {
  it('reassembles data lines split across chunks and skips comments', () => {
    const got: string[] = [];
    const parser = createSseParser((d) => got.push(d));
    parser.push(': OPENROUTER PROCESSING\n\ndata: {"a"');
    parser.push(':1}\r\n\ndata: [DONE]\n');
    expect(got).toEqual(['{"a":1}', '[DONE]']);
  });
});

describe('explain request validation', () => {
  const request: ExplainRequest = { context: context(), history: [], question: '' };
  const envelope = { channel: 'freegaku-4989', source: '4989' } as const;

  it('accepts a valid request and rejects a selection outside the transcript', () => {
    expect(isExplainRequest(request)).toBe(true);
    expect(isExplainRequest({ ...request, context: context({ to: 100 }) })).toBe(false);
    expect(isExplainRequest({ ...request, context: context({ from: 5, to: 4 }) })).toBe(false);
  });

  it('only accepts explain messages in protocol v4 but keeps v3 mining', () => {
    const explain = { ...envelope, type: 'explain', requestId: 'r1', request };
    expect(isM24989PageRequest({ ...explain, version: 4 })).toBe(true);
    expect(isM24989PageRequest({ ...explain, version: 3 })).toBe(false);
    expect(isM24989PageRequest({ ...envelope, version: 3, type: 'probe' })).toBe(true);
    expect(isM24989PageRequest({ ...envelope, version: 5, type: 'probe' })).toBe(false);
    expect(isM24989PageRequest({ ...envelope, version: 4, type: 'explain-cancel', requestId: 'r1' })).toBe(true);
  });
});
