import type { SubtitleCue } from '@migaku2/subtitles';
import type { ExplainContext, ExplainCue, ExplainRequest } from './messages';

// Prompt building for explanations. Pure (no DOM, no network) so the sidebar
// sites and 4989 share one set of rules and it can be unit-tested.

/** Cues after the selection the model may see: enough to finish the scene,
 * not enough to spoil what comes later. */
export const LOOKAHEAD_CUES = 20;
/** Transcript budget in characters (Japanese is roughly a token per char).
 * Beyond it the earliest cues are dropped first. */
export const MAX_TRANSCRIPT_CHARS = 60_000;

export interface ChatTextPart {
  type: 'text';
  text: string;
  cache_control?: { type: 'ephemeral' };
}

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant';
  content: string | ChatTextPart[];
}

const SITE_LABELS: Record<ExplainContext['site'], string> = {
  youtube: 'YouTube',
  netflix: 'Netflix',
  youglish: 'YouGlish (YouTube clips found by searching for a word)',
  '4989': '4989 American Life (YouTube channel; the transcript is the official script)',
};

const LANGUAGE_NAMES: Record<string, string> = {
  ja: 'Japanese',
  en: 'English',
  zh: 'Chinese',
  ko: 'Korean',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
};

export function languageName(code: string): string {
  const base = code.toLowerCase().split(/[-_]/)[0] ?? '';
  return LANGUAGE_NAMES[base] ?? (code || 'the target language');
}

/** Map sidebar cues and a selection to the context sent for explanation. */
export function explainContextFromCues(
  cues: SubtitleCue[],
  selection: { from: number; to: number; selectedText: string },
  meta: Pick<ExplainContext, 'site' | 'title' | 'details' | 'autoGenerated' | 'language'>,
): ExplainContext | null {
  if (selection.from < 0 || selection.to >= cues.length || selection.from > selection.to) return null;
  return {
    ...meta,
    details: meta.details.filter((d) => d.value.trim().length > 0),
    cues: cues.map((c) => ({ text: c.text, startMs: c.start, endMs: c.end })),
    from: selection.from,
    to: selection.to,
    selectedText: selection.selectedText,
  };
}

export interface TranscriptWindow {
  /** Original indexes are kept so the selection can be marked. */
  cues: Array<{ cue: ExplainCue; index: number }>;
  omittedBefore: boolean;
  omittedAfter: boolean;
}

/** Everything up to the selection plus a short lookahead, trimmed from the
 * start to fit the budget. The selection itself is never trimmed. */
export function transcriptWindow(
  context: ExplainContext,
  maxChars = MAX_TRANSCRIPT_CHARS,
  lookahead = LOOKAHEAD_CUES,
): TranscriptWindow {
  const last = Math.min(context.cues.length - 1, context.to + lookahead);
  let first = 0;
  let chars = 0;
  for (let i = last; i >= 0; i--) {
    chars += context.cues[i]!.text.length + 12;
    if (chars > maxChars && i < context.from) {
      first = i + 1;
      break;
    }
  }
  const cues: TranscriptWindow['cues'] = [];
  for (let i = first; i <= last; i++) cues.push({ cue: context.cues[i]!, index: i });
  return { cues, omittedBefore: first > 0, omittedAfter: last < context.cues.length - 1 };
}

export function buildSystemPrompt(context: ExplainContext, explainLanguage: string): string {
  const target = languageName(context.language);
  const parts: string[] = [];
  if (context.autoGenerated) {
    parts.push(
      'IMPORTANT: This transcript was auto-generated by speech recognition and may contain ' +
        'mis-transcriptions. If the selected text looks wrong, say what was probably said ' +
        'instead before explaining it.',
    );
  }
  parts.push(
    `You help a ${target} learner understand something they heard while watching a video. ` +
      'They selected part of the transcript and want to know why it is said the way it is: ' +
      'meaning, nuance, grammar, word choice, register, who is speaking to whom, cultural ' +
      'background, or what is going on in the scene — whatever their question is about.',
    'Ground the explanation in the transcript and the video details. Say when you are ' +
      'inferring something the transcript does not show (for example who is speaking).',
    'The transcript deliberately stops shortly after the selection. Do not speculate about ' +
      'or reveal what happens later in the story.',
    'Lead with the direct answer, then supporting detail. Keep it concise. Use short ' +
      'paragraphs, **bold** for key terms and lists where they help; no tables. Quote ' +
      `${target} as written, adding readings in parentheses for harder words.`,
    `Write in ${explainLanguage || 'English'}. If the learner writes their question in a ` +
      'different language, answer in that language instead.',
  );
  return parts.join('\n\n');
}

export function buildContextBlock(context: ExplainContext): string {
  const lines: string[] = ['<video>', `Site: ${SITE_LABELS[context.site]}`];
  if (context.title) lines.push(`Title: ${context.title}`);
  for (const { label, value } of context.details) lines.push(`${label}: ${value.trim()}`);
  lines.push('</video>', '');

  const window = transcriptWindow(context);
  const language = context.language ? ` language="${context.language}"` : '';
  lines.push(`<transcript${language}>`);
  if (window.omittedBefore) lines.push('(earlier lines omitted)');
  for (const { cue, index } of window.cues) {
    const marker = index >= context.from && index <= context.to ? '▶ ' : '';
    lines.push(`${marker}[${formatClock(cue.startMs)}] ${cue.text.replace(/\s*\n\s*/g, ' ')}`);
  }
  if (window.omittedAfter) lines.push('(transcript continues; not shown)');
  lines.push('</transcript>', '');
  lines.push('Lines marked ▶ contain the selection.');
  lines.push(`<selection>${context.selectedText.trim()}</selection>`);
  return lines.join('\n');
}

export function questionText(question: string): string {
  const q = question.trim();
  return q || 'Explain the selected text.';
}

/** OpenAI-style chat messages for OpenRouter. The context block is its own
 * cache-marked part so follow-ups reuse the cached transcript. */
export function buildExplainMessages(request: ExplainRequest, explainLanguage: string): ChatMessage[] {
  const turns = [...request.history, { question: request.question, answer: '' }];
  const messages: ChatMessage[] = [
    { role: 'system', content: buildSystemPrompt(request.context, explainLanguage) },
  ];
  turns.forEach((turn, i) => {
    if (i === 0) {
      messages.push({
        role: 'user',
        content: [
          {
            type: 'text',
            text: buildContextBlock(request.context),
            cache_control: { type: 'ephemeral' },
          },
          { type: 'text', text: questionText(turn.question) },
        ],
      });
    } else {
      messages.push({ role: 'user', content: questionText(turn.question) });
    }
    if (i < turns.length - 1) messages.push({ role: 'assistant', content: turn.answer });
  });
  return messages;
}

export function formatCost(usd: number): string {
  if (usd <= 0) return '$0';
  if (usd < 0.0001) return '<$0.0001';
  if (usd < 0.01) return `$${Number(usd.toPrecision(3))}`;
  return `$${usd.toFixed(3)}`;
}

/** Incremental server-sent-events parser: feed text chunks, get `data:` payloads. */
export function createSseParser(onData: (data: string) => void): { push(chunk: string): void } {
  let buffer = '';
  return {
    push(chunk: string) {
      buffer += chunk;
      let newline: number;
      while ((newline = buffer.indexOf('\n')) >= 0) {
        const line = buffer.slice(0, newline).replace(/\r$/, '');
        buffer = buffer.slice(newline + 1);
        if (line.startsWith('data:')) onData(line.slice(5).trimStart());
      }
    },
  };
}

function formatClock(ms: number): string {
  const total = Math.max(0, Math.floor(ms / 1000));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const mmss = `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  return h > 0 ? `${h}:${mmss}` : mmss;
}
